/*
* Name:         Ayden Masters 
* Date:         Tuesday, March 23, 2021 13:39:09
* Exercise:     Project 5 Movie Genre Sort / Testing Inheritance
* Class:        COP2552 
* File Name:    InvalidMovieData.java
* 
* Synopsis:     This class will be responsible for the error message that
                will be displayed to the user if improper data is in the file.
                This was done as more of a proof of concept to see exactly how
                this would operate in a scenario where multiple custom errors
                would need to be handled and explaining why they occurred.
*/
public class InvalidMovieData extends Exception {

    /*
     * This was generated by my text editor, I guess this is a unique reference to
     * my exception so I will keep this
     */
    private static final long serialVersionUID = 7889442892549686168L;

    /*
     * Print error to Inform the uer how to properly resolve the issue with the
     * movie listing file
     */
    public InvalidMovieData() {
        super("Error: Movie date in file improperly formatted. Movie data must be formatted like below\n\n"
                + "Steven Spielberg {RETURN} \nJohn Williams {RETURN} \nSchindler's List, 1994, War, R {RETURN}"
                + "\nSaving Private Ryan, 1998, War, R {RETURN}"
                + "\n\nOr like this\n\nDirector Name {RETURN} \nComposer Name {RETURN} \nMovie Name, Year released, Movie Genre, Movie Age rating {RETURN}"
                + "\nNew line for movie info would begin here.\n");
    }
}
